name: CI

on:
  push


jobs:
  Native:
    strategy:
      fail-fast: false
      matrix:
        buildtype: ["debug", "release"]

    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Install deps
        run: |
          python3 -m pip install meson ninja

      - name: Print gcc version
        run: |
          gcc -v

      - name: Test
        run: |
          meson . build -Dbuildtype=${{ matrix.buildtype }}
          cd build
          meson test
  ManyLinux:
    strategy:
      fail-fast: false
      matrix:
        buildtype: ["debug", "release"]

    runs-on: 'ubuntu-latest'
    container:
      image: "quay.io/pypa/manylinux_2_28_x86_64" 

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Install deps
        run: |
          pipx install meson ninja

      - name: Print gcc version
        run: |
          gcc -v

      - name: Test
        run: |
          meson . build -Dbuildtype=${{ matrix.buildtype }}
          cd build
          meson test
